foo

diff --git a/script/bench b/script/bench
--- a/script/bench
+++ b/script/bench
@@ -12,14 +12,19 @@ cleanup() {
 count=5
 tname='^BenchmarkIndexBatch100'
 
-#trap cleanup EXIT
+trap cleanup EXIT
 
 if ! go test -benchmem -run=XXX -bench "$tname" -count $count > new; then
+  echo "Failed benchmarks in new branch"
   cat new
   exit 1
 fi
 
 git checkout master > /dev/null 2>&1
-go test -benchmem -run=XXX -bench "$tname" -count $count > old
+if ! go test -benchmem -run=XXX -bench "$tname" -count $count > old; then
+  echo "Failed benchmarks in old branch"
+  cat old
+  exit 1
+fi
 
 benchstat old new
